version: "3.8"

services:
  api:
    build:
      context: ./API
      dockerfile: Dockerfile
    ports:
      - "5116:5116"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  ui:
    build:
      context: ./UI/accruent-inventory-control
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:5116/api/v1
    depends_on:
      - api
